### ISSUE TITLE
installation problem from source

### ISSUE THREAD

**Issue by longwoo** [georgmartius/lpzrobots#22]
For some reason, I cannot install lpzrobots directly from this way
```
sudo add-apt-repository ppa:georg-martius/lpzrobots
sudo apt-get update
sudo apt-get install guilogger lpzrobots-oderobots
```
 So, I tried to install it from source, however,  it gives me error like this 
```
In file included from simulation.cpp:36:0:
simulation.h:145:32: error: ‘osgGA::GUIEventHandlerVisitor’ has not been declared
     virtual void accept(osgGA::GUIEventHandlerVisitor& v);
                                ^
In file included from simulation.cpp:36:0:
simulation.h:145:32: error: ‘osgGA::GUIEventHandlerVisitor’ has not been declared
     virtual void accept(osgGA::GUIEventHandlerVisitor& v);
                                ^
In file included from simulation.cpp:36:0:
simulation.h:145:32: error: ‘osgGA::GUIEventHandlerVisitor’ has not been declared
     virtual void accept(osgGA::GUIEventHandlerVisitor& v);
                                ^
simulation.cpp:989:34: error: variable or field ‘accept’ declared void
   void Simulation::accept(osgGA::GUIEventHandlerVisitor& v) {
                                  ^
simulation.cpp:989:27: error: ‘GUIEventHandlerVisitor’ is not a member of ‘osgGA’
   void Simulation::accept(osgGA::GUIEventHandlerVisitor& v) {
                           ^
simulation.cpp:989:58: error: ‘v’ was not declared in this scope
   void Simulation::accept(osgGA::GUIEventHandlerVisitor& v) {
                                                          ^
simulation.cpp:989:34: error: variable or field ‘accept’ declared void
   void Simulation::accept(osgGA::GUIEventHandlerVisitor& v) {
                                  ^
simulation.cpp:989:27: error: ‘GUIEventHandlerVisitor’ is not a member of ‘osgGA’
   void Simulation::accept(osgGA::GUIEventHandlerVisitor& v) {
                           ^
simulation.cpp:989:58: error: ‘v’ was not declared in this scope
   void Simulation::accept(osgGA::GUIEventHandlerVisitor& v) {
                                                          ^
simulation.cpp:989:34: error: variable or field ‘accept’ declared void
   void Simulation::accept(osgGA::GUIEventHandlerVisitor& v) {
                                  ^
simulation.cpp:989:27: error: ‘GUIEventHandlerVisitor’ is not a member of ‘osgGA’
   void Simulation::accept(osgGA::GUIEventHandlerVisitor& v) {
                           ^
simulation.cpp:989:58: error: ‘v’ was not declared in this scope
   void Simulation::accept(osgGA::GUIEventHandlerVisitor& v) {
```

Anyone meet this problem before?
By the way, my OS is ubuntu 14.04.

**Comment by georgmartius** [comment]
did you install the dependencies correctly? It looks like openscenegraph-dev 
is not installed or so?

On Sonntag, 7. Mai 2017 23:15:27 CEST longwoo wrote:
> For some reason, I cannot install lpzrobots directly from this way
> ```
> sudo add-apt-repository ppa:georg-martius/lpzrobots
> sudo apt-get update
> sudo apt-get install guilogger lpzrobots-oderobots
> ```
>  So, I tried to install it from source, however,  it gives me error like
> this ```
> In file included from simulation.cpp:36:0:
> simulation.h:145:32: error: ‘osgGA::GUIEventHandlerVisitor’ has not been
> declared virtual void accept(osgGA::GUIEventHandlerVisitor& v);
>                                 ^
> In file included from simulation.cpp:36:0:
> simulation.h:145:32: error: ‘osgGA::GUIEventHandlerVisitor’ has not been
> declared virtual void accept(osgGA::GUIEventHandlerVisitor& v);
>                                 ^
> In file included from simulation.cpp:36:0:
> simulation.h:145:32: error: ‘osgGA::GUIEventHandlerVisitor’ has not been
> declared virtual void accept(osgGA::GUIEventHandlerVisitor& v);
>                                 ^
> simulation.cpp:989:34: error: variable or field ‘accept’ declared void
>    void Simulation::accept(osgGA::GUIEventHandlerVisitor& v) {
>                                   ^
> simulation.cpp:989:27: error: ‘GUIEventHandlerVisitor’ is not a member of
> ‘osgGA’ void Simulation::accept(osgGA::GUIEventHandlerVisitor& v) {
>                            ^
> simulation.cpp:989:58: error: ‘v’ was not declared in this scope
>    void Simulation::accept(osgGA::GUIEventHandlerVisitor& v) {
>                                                           ^
> simulation.cpp:989:34: error: variable or field ‘accept’ declared void
>    void Simulation::accept(osgGA::GUIEventHandlerVisitor& v) {
>                                   ^
> simulation.cpp:989:27: error: ‘GUIEventHandlerVisitor’ is not a member of
> ‘osgGA’ void Simulation::accept(osgGA::GUIEventHandlerVisitor& v) {
>                            ^
> simulation.cpp:989:58: error: ‘v’ was not declared in this scope
>    void Simulation::accept(osgGA::GUIEventHandlerVisitor& v) {
>                                                           ^
> simulation.cpp:989:34: error: variable or field ‘accept’ declared void
>    void Simulation::accept(osgGA::GUIEventHandlerVisitor& v) {
>                                   ^
> simulation.cpp:989:27: error: ‘GUIEventHandlerVisitor’ is not a member of
> ‘osgGA’ void Simulation::accept(osgGA::GUIEventHandlerVisitor& v) {
>                            ^
> simulation.cpp:989:58: error: ‘v’ was not declared in this scope
>    void Simulation::accept(osgGA::GUIEventHandlerVisitor& v) {
> ```
> 
> Anyone meet this problem before?
> By the way, my OS is ubuntu 14.04.


-- 
-----------------------------------------------------------------
Dr. Georg Martius
Phone: +49 7071 601 1719
Office: S2.003
Group Leader
Autonomous Learning Group
Max Plank Institute for Intelligent Systems
Spemannstr 34, 72076 Tuebingen, Germany

**Comment by longwoo** [comment]
Thanks. But I have installed the dependencies by the following cmd
```
sudo apt-get install g++ make automake libtool xutils-dev m4 libreadline-dev libgsl0-dev libglu-dev libgl1-mesa-dev freeglut3-dev libopenscenegraph-dev libqt4-dev libqt4-opengl libqt4-opengl-dev qt4-qmake libqt4-qt3support gnuplot gnuplot-x11 libncurses5-dev
```

which gives me 
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'libglu1-mesa-dev' instead of 'libglu-dev'
automake is already the newest version.
freeglut3-dev is already the newest version.
g++ is already the newest version.
libglu1-mesa-dev is already the newest version.
libgsl0-dev is already the newest version.
libncurses5-dev is already the newest version.
libreadline-dev is already the newest version.
libtool is already the newest version.
m4 is already the newest version.
make is already the newest version.
xutils-dev is already the newest version.
gnuplot is already the newest version.
gnuplot-x11 is already the newest version.
libgl1-mesa-dev is already the newest version.
libqt4-dev is already the newest version.
libqt4-opengl is already the newest version.
libqt4-opengl-dev is already the newest version.
libqt4-qt3support is already the newest version.
qt4-qmake is already the newest version.
libopenscenegraph-dev is already the newest version.
The following packages were automatically installed and are no longer required:
  gazebo4 gazebo4-common gazebo4-plugin-base hddtemp liballegro4.4
  liballegro4.4-plugin-alsa libbullet2.82 libbullet2.82-dev libcegui-mk2-0.7.6
  libcegui-mk2-dev libdevil-dev libdevil1c2 libfltk1.1 libfltk1.1-dev
  libgazebo4 libgazebo4-dev libgeos-dev libgnomecanvas2-0
  libgnomecanvas2-common libgts-0.7-5 libgts-bin libgts-dev liblcms1
  liblcms1-dev liblcms2-dev liblodo3.0 liblua5.1-0-dev libmng-dev libois-1.3.0
  libplayerc++3.0 libplayerc++3.0-dev libplayerc3.0 libplayerc3.0-dev
  libplayercommon3.0 libplayercommon3.0-dev libplayercore3.0
  libplayercore3.0-dev libplayerdrivers3.0 libplayerdrivers3.0-dev
  libplayerinterface3.0 libplayerinterface3.0-dev libplayerjpeg3.0
  libplayerjpeg3.0-dev libplayertcp3.0 libplayertcp3.0-dev libplayerwkb3.0
  libplayerwkb3.0-dev libpmap3.0 libprotoc-dev libsdformat2 libsdformat2-dev
  libsilly libsimbody-dev libsimbody3.5 libstatgrab9 libtar-dev libtar0
  libtbb-dev liburdfdom-tools osrf-common robot-player robot-player-dev
  ros-indigo-common-tutorials ros-indigo-desktop
  ros-indigo-diagnostic-analysis ros-indigo-diagnostic-common-diagnostics
  ros-indigo-diagnostics ros-indigo-executive-smach ros-indigo-gazebo4-msgs
  ros-indigo-gazebo4-plugins ros-indigo-gazebo4-ros
  ros-indigo-geometry-tutorials ros-indigo-interactive-marker-tutorials
  ros-indigo-laser-pipeline ros-indigo-librviz-tutorial
  ros-indigo-nodelet-tutorial-math ros-indigo-perception
  ros-indigo-perception-pcl ros-indigo-pluginlib-tutorials
  ros-indigo-pointcloud-to-laserscan ros-indigo-robot ros-indigo-robot-model
  ros-indigo-ros-tutorials ros-indigo-rospy-tutorials
  ros-indigo-rviz-plugin-tutorials ros-indigo-rviz-python-tutorial
  ros-indigo-smach ros-indigo-smach-msgs ros-indigo-smach-ros ros-indigo-stage
  ros-indigo-stage-ros ros-indigo-turtle-actionlib ros-indigo-turtle-tf
  ros-indigo-turtle-tf2 ros-indigo-turtlesim ros-indigo-urdf-tutorial
  ros-indigo-visualization-marker-tutorials ros-indigo-visualization-tutorials
  sandia-hand sdformat-sdf ttf-dejavu-core
Use 'apt-get autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 503 not upgraded.
```

**Comment by janbraun** [comment]
Hi!

I had problems using openscenegraph > 3.2. Only after downgrading to 
openscenegraph 3.2 I was able to compile lpzrobots again. Probably you are 
having version 3.4 or newer installed?

Cheers,

Jan

Am Montag, 8. Mai 2017, 13:23:44 CEST schrieb longwoo:
> Thanks. But I have installed the dependencies by the following cmd
> ```
> sudo apt-get install g++ make automake libtool xutils-dev m4 libreadline-dev
> libgsl0-dev libglu-dev libgl1-mesa-dev freeglut3-dev libopenscenegraph-dev
> libqt4-dev libqt4-opengl libqt4-opengl-dev qt4-qmake libqt4-qt3support
> gnuplot gnuplot-x11 libncurses5-dev ```
> 
> which gives me
> ```
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> Note, selecting 'libglu1-mesa-dev' instead of 'libglu-dev'
> automake is already the newest version.
> freeglut3-dev is already the newest version.
> g++ is already the newest version.
> libglu1-mesa-dev is already the newest version.
> libgsl0-dev is already the newest version.
> libncurses5-dev is already the newest version.
> libreadline-dev is already the newest version.
> libtool is already the newest version.
> m4 is already the newest version.
> make is already the newest version.
> xutils-dev is already the newest version.
> gnuplot is already the newest version.
> gnuplot-x11 is already the newest version.
> libgl1-mesa-dev is already the newest version.
> libqt4-dev is already the newest version.
> libqt4-opengl is already the newest version.
> libqt4-opengl-dev is already the newest version.
> libqt4-qt3support is already the newest version.
> qt4-qmake is already the newest version.
> libopenscenegraph-dev is already the newest version.
> The following packages were automatically installed and are no longer
> required: gazebo4 gazebo4-common gazebo4-plugin-base hddtemp liballegro4.4
> liballegro4.4-plugin-alsa libbullet2.82 libbullet2.82-dev
> libcegui-mk2-0.7.6 libcegui-mk2-dev libdevil-dev libdevil1c2 libfltk1.1
> libfltk1.1-dev libgazebo4 libgazebo4-dev libgeos-dev libgnomecanvas2-0
>   libgnomecanvas2-common libgts-0.7-5 libgts-bin libgts-dev liblcms1
>   liblcms1-dev liblcms2-dev liblodo3.0 liblua5.1-0-dev libmng-dev
> libois-1.3.0 libplayerc++3.0 libplayerc++3.0-dev libplayerc3.0
> libplayerc3.0-dev libplayercommon3.0 libplayercommon3.0-dev
> libplayercore3.0
>   libplayercore3.0-dev libplayerdrivers3.0 libplayerdrivers3.0-dev
>   libplayerinterface3.0 libplayerinterface3.0-dev libplayerjpeg3.0
>   libplayerjpeg3.0-dev libplayertcp3.0 libplayertcp3.0-dev libplayerwkb3.0
>   libplayerwkb3.0-dev libpmap3.0 libprotoc-dev libsdformat2 libsdformat2-dev
> libsilly libsimbody-dev libsimbody3.5 libstatgrab9 libtar-dev libtar0
> libtbb-dev liburdfdom-tools osrf-common robot-player robot-player-dev
> ros-indigo-common-tutorials ros-indigo-desktop
>   ros-indigo-diagnostic-analysis ros-indigo-diagnostic-common-diagnostics
>   ros-indigo-diagnostics ros-indigo-executive-smach ros-indigo-gazebo4-msgs
>   ros-indigo-gazebo4-plugins ros-indigo-gazebo4-ros
>   ros-indigo-geometry-tutorials ros-indigo-interactive-marker-tutorials
>   ros-indigo-laser-pipeline ros-indigo-librviz-tutorial
>   ros-indigo-nodelet-tutorial-math ros-indigo-perception
>   ros-indigo-perception-pcl ros-indigo-pluginlib-tutorials
>   ros-indigo-pointcloud-to-laserscan ros-indigo-robot ros-indigo-robot-model
> ros-indigo-ros-tutorials ros-indigo-rospy-tutorials
>   ros-indigo-rviz-plugin-tutorials ros-indigo-rviz-python-tutorial
>   ros-indigo-smach ros-indigo-smach-msgs ros-indigo-smach-ros
> ros-indigo-stage ros-indigo-stage-ros ros-indigo-turtle-actionlib
> ros-indigo-turtle-tf ros-indigo-turtle-tf2 ros-indigo-turtlesim
> ros-indigo-urdf-tutorial ros-indigo-visualization-marker-tutorials
> ros-indigo-visualization-tutorials sandia-hand sdformat-sdf ttf-dejavu-core
> Use 'apt-get autoremove' to remove them.
> 0 upgraded, 0 newly installed, 0 to remove and 503 not upgraded.
> ```

**Comment by longwoo** [comment]
@janbraun thanks. I tried to reinstall openscenegraph3.2.0 from source , but it didn't work. It gives the same error.

**Comment by richardharmadi** [comment]
@longwoo Hi I find this problem in macOSX too. I get to know that GUIEventHandlerVisitor is deprecated from OSG, and you can actually comment the part that using GUIEventHandlerVisitor (e.g the 'accept' function)

cmiiw, you can find out more [here](http://osg-users.openscenegraph.narkive.com/o11k42ph/removing-unused-classes-in-osgga) 

and by the way I could install the simulator in Ubuntu 16.04 with no problem at all, using the libopenscenegraph-dev

**Comment by longwoo** [comment]
@richardharmadi Excellent! It works for me. Thanks.

**Comment by georgmartius** [comment]
I think this should be fixed by now with the code by scheunemann. I merged it into master
