### ISSUE TITLE
installation problem on MacOSX

### ISSUE THREAD

**Issue by richardharmadi** [georgmartius/lpzrobots#23]
Hi

I've been trying to install the simulator on my Mac. I've found several problems, and get away with it, but at this point, I am stuck with this error:

`osg/lpzhelphandler.cpp: In member function 'void lpzrobots::LpzHelpHandler::setUpScene(osgViewer::ViewerBase*)':
osg/lpzhelphandler.cpp:189:37: error: 'const BoundingSphere' has no member named 'xMax'
         pos.x() = label->getBound().xMax();`

I see that in both OpenSceneGraph [library](http://www.openscenegraph.org/index.php/download-section/stable-releases), there is no xMax function in BoundingSphere.

*note : I installed the OpenSceneGraph library using HomeBrew

But I have no problem installing this simulator in Ubuntu, which using the libopenscenegraph-dev.

Is there any way to get this around? Thanks in advance.

**Comment by scheunemann** [comment]
There has been a change that `getBound()` returns a `const BoundingSphere&` instead of a BoundingBox.  `getBoundingBox().xMax() and it compiles fine. I did do some other changes for running the code on Arch Linux here: https://github.com/scheunemann/lpzrobots/tree/fixes-for-newer-libs

**Comment by georgmartius** [comment]
I merged this with some minor changes into the master branch now

**Comment by jerryzhao173985** [comment]
Hi Richard, 

I know this is an old post. Have you managed to get lpzrobot working on macOS, I want to install this on Mac but run into a few problems, can I ask you if you have compiled Lpzrobots on macOS successfully?

Jerry
